build.gradle
src/main/java/umc/catchy/global/common/response/BaseResponse.java
src/main/java/umc/catchy/global/common/response/code/BaseCode.java
src/main/java/umc/catchy/global/common/response/code/BaseErrorCode.java
src/main/java/umc/catchy/global/common/response/code/ErrorReasonDTO.java
src/main/java/umc/catchy/global/common/response/code/ReasonDTO.java
src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
src/main/java/umc/catchy/global/common/response/status/SuccessStatus.java
src/main/java/umc/catchy/global/error/exception/ExceptionAdvice.java
src/main/java/umc/catchy/global/error/exception/GeneralException.java

- close #2 
- 응답통일, 공통 예외처리
- validation 의존성 추가했습니다
- "isSuccess", "code", "message", "result" 형식으로 응답 통일했습니다
- errorstatus에 기본 에러만 설정해놔서 작업하시면서 에러 추가하면 될 것 같습니다

feat: 응답통일, 공통 예외처리

---

build.gradle
src/main/java/umc/catchy/domain/group/domain/Groups.java
src/main/java/umc/catchy/domain/like/domain/Likes.java
src/main/java/umc/catchy/domain/mapping/memberGroup/domain/MemberGroup.java
src/main/java/umc/catchy/domain/mapping/placeCourse/domain/PlaceCourse.java
src/main/java/umc/catchy/domain/vote/domain/Vote.java
src/main/java/umc/catchy/global/config/swagger/SwaggerConfig.java
src/main/resources/application.properties
src/main/resources/application.yml

- close #4 
- Swagger 설정 및 .yml 파일 설정
- Swagger 설정을 위한 config 파일을 생성했습니다.
- Group과 Like 도메인이 데이터베이스 예약어로 테이블 생성이 안되는 오류가 발생해 도메인명을 변경하였습니다. (Groups, Likes)
- h2 데이터베이스 연결을 위한 yml 파일을 설정하였습니다.
- 
- 
- https://herojoon-dev.tistory.com/141

feat: Swagger 설정

---

src/main/java/umc/catchy/domain/member/api/MemberController.java
src/main/java/umc/catchy/domain/member/domain/Member.java
src/main/java/umc/catchy/domain/member/dto/request/ProfileRequest.java
src/main/java/umc/catchy/domain/member/dto/response/ProfileResponse.java
src/main/java/umc/catchy/domain/member/service/MemberService.java

- close #18 
- 프로필 조회 및 수정
- 프로필 조회 및 수정 기능 구현
- Controller description 수정
- memberService 코드 정렬
- 프로필 조회
- 프로필 수정(닉네임 중복일 때)
- 프로필 수정

[feature] 개인정보(프로필) 조회 및 수정

---

src/main/java/umc/catchy/domain/group/api/GroupController.java
src/main/java/umc/catchy/domain/group/dto/request/CreateGroupRequest.java
src/main/java/umc/catchy/domain/group/dto/response/CreateGroupResponse.java
src/main/java/umc/catchy/domain/group/service/GroupService.java
src/main/resources/application-local.yml

- close #23 
- 그룹 생성 API 구현
- multipart/form-data 형식으로 응답 요청하도록 구현했습니다.
- 사진은 S3 설정되면 수정하겠습니다.
- ![화면 캡처 2025-01-12 182100](https://github.com/user-attachments/assets/390fdf97-3eed-4024-97a0-bb14c46f5ddc)
- 사진에는 inviteCode가 null로 응답됐는데, 이 부분은 수정했습니다.
- 
-

[feature] 그룹-그룹 생성하기

---

src/main/java/umc/catchy/domain/category/dao/CategoryRepository.java
src/main/java/umc/catchy/domain/category/dto/request/CategorySurveyRequest.java
src/main/java/umc/catchy/domain/categoryVote/domain/CategoryVote.java
src/main/java/umc/catchy/domain/mapping/memberCategory/dao/MemberCategoryRepository.java
src/main/java/umc/catchy/domain/mapping/memberCategory/domain/MemberCategory.java
src/main/java/umc/catchy/domain/mapping/memberCategory/dto/response/MemberCategoryCreatedResponse.java
src/main/java/umc/catchy/domain/member/api/MemberController.java
src/main/java/umc/catchy/domain/member/service/MemberService.java
src/main/resources/application-local.yml

- close #21 
- 사용자 취향설문 1,2단계 설정 
- 사용자 취향설문을 Request를 받으면 해당 이름을 가진 카테고리를 찾아 사용자에게 저장
- 
- Builder를 잘못 설정해 StackOverFlow에러가 발생했었습니다 ^^;;
-

[feature] 취향설문 1,2단계 설정

---

.gitignore
src/main/java/umc/catchy/domain/activetime/dao/ActiveTimeRepository.java
src/main/java/umc/catchy/domain/activetime/domain/ActiveTime.java
src/main/java/umc/catchy/domain/category/domain/BigCategory.java
src/main/java/umc/catchy/domain/mapping/memberActivetime/dao/MemberActiveTimeRepository.java
src/main/java/umc/catchy/domain/mapping/memberActivetime/domain/MemberActiveTime.java
src/main/java/umc/catchy/domain/mapping/memberStyle/dao/MemberStyleRepository.java
src/main/java/umc/catchy/domain/mapping/memberStyle/domain/MemberStyle.java
src/main/java/umc/catchy/domain/member/api/MemberController.java
src/main/java/umc/catchy/domain/member/dto/request/StyleAndActiveTimeSurveyRequest.java
src/main/java/umc/catchy/domain/member/dto/response/StyleAndActiveTimeSurveyCreatedResponse.java
src/main/java/umc/catchy/domain/member/service/MemberService.java
src/main/java/umc/catchy/domain/style/dao/StyleRepository.java
src/main/java/umc/catchy/domain/style/domain/StyleName.java
src/main/resources/application-local.yml

- close #27 
- 사용자 참여 스타일 DTO,DAO 설계
- 사용자 활동 요일, 시간 DTO,DAO 설계 (활동시간 데이터 타입 변환 LocalDateTime -> LocalTime)
- 설문조사 3,4단계 서비스, 컨트롤러 구현
- 대카테고리, 활동 스타일 열거형 value 값 한글로 전환 (ex: 'CAFE' -> '카페')
- 취향설문 3,4단계 (참여 스타일 및 요일, 시간)
- 대카테고리, 활동 스타일 열거형 value 값 한글로 전환
- API KEY 값 커밋을 잘못해서 브랜치가 fix가 됐습니다. 😭

[feature] 취향설문 3,4단계 (참여 스타일 및 요일, 시간)

---

src/main/java/umc/catchy/domain/group/api/GroupController.java
src/main/java/umc/catchy/domain/group/service/GroupService.java
src/main/java/umc/catchy/domain/mapping/memberGroup/dao/MemberGroupRepository.java
src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java

- close #31 
- 그룹 탈퇴 기능
- 그룹 탈퇴 기능

[feature] 그룹 탈퇴

---

src/main/java/umc/catchy/domain/group/api/GroupController.java
src/main/java/umc/catchy/domain/group/dto/response/GroupCalendarResponse.java
src/main/java/umc/catchy/domain/group/service/GroupService.java
src/main/java/umc/catchy/domain/mapping/memberGroup/dao/MemberGroupRepository.java
src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java

- close #35 
- 캘린더-그룹 조회
- 캘린더에서 사용자가 속한 그룹 정보 조회기능

[feature] 캘린더-그룹 조회

---

src/main/java/umc/catchy/domain/vote/api/VoteController.java
src/main/java/umc/catchy/domain/vote/dao/VoteRepository.java
src/main/java/umc/catchy/domain/vote/domain/Vote.java
src/main/java/umc/catchy/domain/vote/dto/request/CreateVoteRequest.java
src/main/java/umc/catchy/domain/vote/dto/response/VoteResponse.java
src/main/java/umc/catchy/domain/vote/service/VoteService.java

- close #37 
- 투표 생성 기능 구현
- end_time은 투표 생성 기준 하루 뒤로 설정했습니다.
- 투표 생성 시 status는 'IN_PROGRESS'로 저장되게 했습니다.

[feature] 투표 생성하기

---

src/main/java/umc/catchy/domain/categoryVote/dao/CategoryVoteRepository.java
src/main/java/umc/catchy/domain/categoryVote/domain/CategoryVote.java
src/main/java/umc/catchy/domain/mapping/memberCategoryVote/dao/MemberCategoryVoteRepository.java
src/main/java/umc/catchy/domain/mapping/memberCategoryVote/domain/MemberCategoryVote.java
src/main/java/umc/catchy/domain/mapping/memberGroup/dao/MemberGroupRepository.java
src/main/java/umc/catchy/domain/vote/api/VoteController.java
src/main/java/umc/catchy/domain/vote/domain/Vote.java
src/main/java/umc/catchy/domain/vote/dto/request/SubmitVoteRequest.java
src/main/java/umc/catchy/domain/vote/dto/response/CategoryDto.java
src/main/java/umc/catchy/domain/vote/dto/response/CategoryResponse.java
src/main/java/umc/catchy/domain/vote/dto/response/GroupVoteStatusResponse.java
src/main/java/umc/catchy/domain/vote/dto/response/MemberVoteStatus.java
src/main/java/umc/catchy/domain/vote/dto/response/VoteResult.java
src/main/java/umc/catchy/domain/vote/dto/response/VoteResultResponse.java
src/main/java/umc/catchy/domain/vote/dto/response/VotedMemberResponse.java
src/main/java/umc/catchy/domain/vote/service/VoteService.java
src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java

- close #44 
- 카테고리 투표 관련 API
- 투표하기 생성 시 카테고리 투표 자동 생성되도록 구현
- 투표하기 구현
- 카테고리 별 id 정보 조회 구현
- 투표 진행 중 투표 현황 조회 구현
- 투표 진행 중 멤버 조회 구현
- 카테고리 id 목록 조회
- 투표 진행 중 투표 현황
- 투표 진행 중 멤버 현황
- 코드가 너무 지저분한데 나중에 리팩토링 하겠습니다 😂

[feature] 카테고리 투표하기

---

src/main/java/umc/catchy/domain/vote/service/VoteService.java

- close #52
- 중복 투표 방지
- voteId를 조회하여 이미 투표한 내역이 있으면 예외처리
-

[fix] 중복 투표 방지 검증

---

src/main/java/umc/catchy/domain/course/api/CourseController.java
src/main/java/umc/catchy/domain/course/domain/Course.java
src/main/java/umc/catchy/domain/courseReview/converter/CourseReviewConverter.java
src/main/java/umc/catchy/domain/courseReview/dao/CourseReviewRepository.java
src/main/java/umc/catchy/domain/courseReview/domain/CourseReview.java
src/main/java/umc/catchy/domain/courseReview/dto/request/PostCourseReviewRequest.java
src/main/java/umc/catchy/domain/courseReview/dto/response/PostCourseReviewResponse.java
src/main/java/umc/catchy/domain/courseReview/service/CourseReviewService.java
src/main/java/umc/catchy/domain/courseReviewImage/converter/CourseReviewImageConverter.java
src/main/java/umc/catchy/domain/courseReviewImage/dao/CourseReviewImageRepository.java
src/main/java/umc/catchy/domain/courseReviewImage/domain/CourseReviewImage.java
src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepository.java
src/main/java/umc/catchy/domain/mapping/memberCourse/domain/MemberCourse.java
src/main/java/umc/catchy/domain/placeReview/service/PlaceReviewService.java
src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java

- close #56 
- 코스 리뷰 작성 기능 구현
- 코스 리뷰 작성 API 구현
- 멤버의 코스 참여 여부 확인(valid)
- 코스 리뷰 생성 시 Course::hasReview 확인 및 갱신

[feature] 코스 리뷰 작성 API

---

src/main/java/umc/catchy/domain/course/api/CourseController.java
src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepository.java
src/main/java/umc/catchy/domain/mapping/memberCourse/domain/MemberCourse.java
src/main/java/umc/catchy/domain/mapping/memberCourse/dto/response/CourseBookmarkResponse.java
src/main/java/umc/catchy/domain/mapping/memberCourse/service/MemberCourseService.java
src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
src/main/resources/application-local.yml

- close #65 
- 코스 북마크 기능 추가
- 사용자_코스 도메인에서 북마크 기본 설정값 false로 설정
- 사용자_코스 북마크 기능 추가(전환)
- local.yml 파일 jwt 부분 들여쓰기 수정했습니다.
- 성공 
- 사용자코스에 없는 코스id 값을 pathvariable로 준 경우
-
-

[feature] 코스 찜하기

---

src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
src/main/java/umc/catchy/domain/mapping/placeVisit/domain/PlaceVisit.java
src/main/java/umc/catchy/domain/mapping/placeVisit/dto/response/PlaceLikedResponse.java
src/main/java/umc/catchy/domain/mapping/placeVisit/service/PlaceVisitService.java
src/main/java/umc/catchy/domain/place/api/PlaceController.java

- close #66 
- 장소 좋아요 기능 추가 
- 장소_방문 도메인에서 isLiked 기본 설정값 false로 변경
- 장소 좋아요 기능 추가 (좋아요 전환).
- 성공
- 없는 장소id를 넘겨주었을 때
- 
-

[feature] 장소 좋아요

---

src/main/java/umc/catchy/domain/category/dao/CategoryRepository.java
src/main/java/umc/catchy/domain/categoryVote/dao/CategoryVoteRepository.java
src/main/java/umc/catchy/domain/categoryVote/domain/CategoryVote.java
src/main/java/umc/catchy/domain/group/domain/Groups.java
src/main/java/umc/catchy/domain/mapping/memberCategoryVote/dao/MemberCategoryVoteRepository.java
src/main/java/umc/catchy/domain/place/dao/PlaceRepository.java
src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepository.java
src/main/java/umc/catchy/domain/vote/api/VoteController.java
src/main/java/umc/catchy/domain/vote/dto/response/CategoryResult.java
src/main/java/umc/catchy/domain/vote/dto/response/GroupPlaceResponse.java
src/main/java/umc/catchy/domain/vote/dto/response/GroupVoteResultResponse.java
src/main/java/umc/catchy/domain/vote/dto/response/PlaceResponse.java
src/main/java/umc/catchy/domain/vote/dto/response/VoteResultResponse.java
src/main/java/umc/catchy/domain/vote/service/VoteService.java

- close #54 
- 투표 완료 카테고리, 장소 확인
- 투표 완료(카테고리 확인) 조회 구현 : 투표 결과에서 과반수 이상 투표한 카테고리 + 그룹 장소 기반 필터링
- 투표 완료(장소 확인) 조회 구현 : 그룹 장소 기반 필터링
- 투표 완료(카테고리 확인)
- ![투표 완료 - 카테고리 확인](https://github.com/user-attachments/assets/df790725-f1d8-4238-91dc-d33dda57f366)
- 투표 완료(장소 확인)
- ![투표 완료 - 카테고리 별 장소 확인](https://github.com/user-attachments/assets/eda56df6-a2a9-4a90-9348-e9e6ff9d2bae)
장소 좋아요 기능 개발 후 조회 부분 수정할 예정입니다.
- 투표기능 다 끝내고 dto 정리하겠습니다...

[feature] 투표 완료 카테고리, 장소 확인

---

src/main/java/umc/catchy/domain/place/domain/Place.java

- close #86 
- 장소 카테고리 매핑관계 수정
- 장소 카테고리 매핑관계 1대1 에서 1대 다로 수정
- 
- 
-

[fix] 장소 카테고리 매핑관계 수정

---

src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml

- close #93 
- 간단한 오류수정입니다.
- 오류 해결 완료

[fix] 내 위치 기반 검색 안되던 오류 수정

---

src/main/java/umc/catchy/domain/activetime/dao/ActiveTimeRepository.java
src/main/java/umc/catchy/domain/activetime/domain/ActiveTime.java
src/main/java/umc/catchy/domain/activetime/dto/ActiveTimeRequest.java
src/main/java/umc/catchy/domain/mapping/memberCategory/dto/response/MemberCategoryCreatedResponse.java
src/main/java/umc/catchy/domain/member/dto/request/StyleAndActiveTimeSurveyRequest.java
src/main/java/umc/catchy/domain/member/service/MemberService.java

- close #97 
- 사용자 취향 설문 로직 에러사항 수정 및 응답 변경
- 사용자 취향설문 3,4단계 서비스 로직이 논리적으로 안맞아 수정했습니다.
- 사용자 취향설문 1,2단계 응답을 수정했습니다.
- 사용자 취향설문 1,2단계 응답 수정본
- 
-

[fix] 사용자 취향 설문 로직 및 응답 수정

---

src/main/java/umc/catchy/domain/course/service/CourseService.java

[fix] 불필요한 import 제거

---

src/main/java/umc/catchy/domain/course/service/CourseService.java
src/main/java/umc/catchy/infra/aws/s3/AmazonS3Manager.java

- close #106 
- AI 추천 코스 이미지 생성
- S3 이미지 업로드 함수 수정
- 
- 예를 들어 "courseName": "한식과 커피를 즐기는 하루", "courseDescription": "한식과 커피로 행복한 하루를 보내요." 이렇게 생성이 되었다고 했을 때, ai가 생성하는 이미지가 코스설명과 동떨어지는 느낌이 있습니다. https://catchy-bucket.s3.ap-northeast-2.amazonaws.com/course-images/3a105ca6-b630-4048-a43a-73e35930131d.png
- DALL-E 모델이 프롬포트를 구체적으로 작성을 해줘야 이미지가 잘 생성되는데, 추천코스가 어떻게 생성될지 모르기때문에 구체적으로 작성하는데 한계가 있어서 어떻게 하면 좋을지 고민입니다...

[fix] AI 추천 코스 이미지 생성

---

src/main/java/umc/catchy/domain/group/dto/request/CreateGroupRequest.java
src/main/java/umc/catchy/domain/group/service/GroupService.java

- close #108 
- promiseTime을 LocalDateTime 형식으로 처리
- 약속 시간 입력 형식 'yyyy-MM-dd HH:mm'으로 정의

[fix] 그룹 생성 - promiseTime을 LocalDateTime 형식으로 처리

---

src/main/java/umc/catchy/domain/category/domain/BigCategory.java
src/main/java/umc/catchy/domain/category/domain/Category.java
src/main/java/umc/catchy/domain/course/api/CourseController.java
src/main/java/umc/catchy/domain/mapping/placeCourse/api/PlaceCourseController.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoPreview.java
src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
src/main/java/umc/catchy/domain/place/domain/Place.java
src/main/java/umc/catchy/domain/place/dto/request/SetCategoryRequest.java
src/main/java/umc/catchy/domain/place/service/PlaceService.java
src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java

- close #113 
- 장소 카테고리 지정 API 구현
예외처리
카테고리 지정 후 장소 조회

[feature] 장소 카테고리 지정 API 구현

---

src/main/java/umc/catchy/domain/course/domain/CourseType.java
src/main/java/umc/catchy/domain/course/service/CourseService.java
src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepositoryImpl.java
src/main/java/umc/catchy/domain/mapping/memberCourse/dto/response/MemberCourseResponse.java

- close #116 
- 코스타입, 대카테고리 enum 출력 방식 변경
- 코스타입: enum명 변경
- 대카테고리: Response에 List String값을 갖도록 변경
.

[fix] enum 출력 형식 변경

---

src/main/java/umc/catchy/domain/category/dao/CategoryRepository.java
src/main/java/umc/catchy/domain/course/service/CourseService.java
src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
src/main/java/umc/catchy/domain/place/dao/PlaceCustomRepository.java
src/main/java/umc/catchy/domain/place/dao/PlaceRepository.java
src/main/java/umc/catchy/domain/place/dao/PlaceRepositoryImpl.java

- close #118 
- AI 추천 코스 - 필터링 적용
- 카테고리 및 지역 필터링 조건을 QueryDSL로 작성
- 필터링된 장소 리스트에서 사용자 행동 데이터(좋아요, 방문)를 기반으로 가중치를 부여하여 정렬

[fix] AI 추천 코스 - 필터링 적용

---

src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
src/main/java/umc/catchy/domain/mapping/placeVisit/domain/PlaceVisit.java
src/main/java/umc/catchy/domain/mapping/placeVisit/dto/response/PlaceVisitedDateResponse.java
src/main/java/umc/catchy/domain/mapping/placeVisit/service/PlaceVisitService.java
src/main/java/umc/catchy/domain/place/api/PlaceController.java
src/main/java/umc/catchy/domain/placeReview/converter/PlaceReviewConverter.java
src/main/java/umc/catchy/domain/placeReview/dto/response/PostPlaceReviewResponse.java
src/main/java/umc/catchy/domain/placeReview/service/PlaceReviewService.java

- close #126 
- 리뷰 작성 시 방문 일자 조회
- 해당 장소를 방문한 날짜를 가져온다.
- 성공
- 
-

[feature] 리뷰 작성 시 방문 일자 조회

---

src/main/java/umc/catchy/domain/vote/dao/VoteRepository.java
src/main/java/umc/catchy/domain/vote/service/VoteService.java
src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java

- close #131 
- 그룹 내 투표 조회 검증
- voteId가 요청한 groupId에 속하는지 검증 추가
-

[fix] 그룹 내 투표 조회 검증

---

src/main/java/umc/catchy/global/common/response/BaseResponse.java
src/main/java/umc/catchy/global/error/exception/ExceptionAdvice.java
src/main/java/umc/catchy/global/error/exception/ResultEmptyListException.java

- close #136 
- 커스텀 예외 추가
- 특정 예외 발생 시 result: []을 반환하는 커스텀 예외(ResultEmptyListException)를 추가
- result: [] 반환 필요 시 GeneralException대신 ResultEmptyListException사용하면 됩니다.

[feature] 커스텀 예외 추가

---

src/main/java/umc/catchy/domain/member/api/MemberController.java
src/main/java/umc/catchy/domain/member/dto/response/NicknameResponse.java
src/main/java/umc/catchy/domain/member/dto/response/ProfileImageResponse.java
src/main/java/umc/catchy/domain/member/dto/response/ProfileResponse.java
src/main/java/umc/catchy/domain/member/service/MemberService.java
src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java

- close #120 
- 장소 검색 response 변경
- 프로필 조회 오류 수정
- 장소 검색 response 변경 (소카테고리 -> 대카테코리)
- 프로필 변경 오류 수정 (프로필 사진이 없는 사용자 조회시) 
- 프로필 관련 response 수정

[fix] response 수정 및 오류 수정

---

src/main/java/umc/catchy/domain/course/converter/CourseConverter.java
src/main/java/umc/catchy/domain/course/service/CourseService.java

- close #114 
- 코스 생성(DIY) 평점 계산
- 코스 생성(DIY) 평점 계산 로직 추가

[fix] 코스 생성(DIY) 시 평점 계산 로직 추가

---

src/main/java/umc/catchy/domain/course/domain/Course.java
src/main/java/umc/catchy/domain/course/service/CourseService.java

- close #140
- Course 도메인 @Enumerated(EnumType.STRING) 변경
- Course 도메인에 converter 적용한거 취소하고 다시 원래대로 복귀했습니다..

[fix] Course 도메인 @Enumerated(EnumType.STRING) 변경

---

src/main/java/umc/catchy/global/config/swagger/SwaggerConfig.java

- close #144 
- 도메인 주소 Swagger 적용
- 도메인 주소에서 Swagger가 작동할 수 있도록 설정
https://yeon-dev.tistory.com/249

[chore] SwaggerConfig 설정

---

src/main/java/umc/catchy/domain/course/domain/Course.java
src/main/java/umc/catchy/domain/course/service/CourseService.java
src/main/java/umc/catchy/domain/course/service/GPTCourseService.java
src/main/java/umc/catchy/domain/course/util/LocationUtils.java
src/main/java/umc/catchy/domain/place/dao/PlaceRepository.java
src/main/java/umc/catchy/domain/place/dao/PlaceRepositoryImpl.java
src/main/java/umc/catchy/domain/vote/service/VoteService.java

- close #146 
- 상위지역 필터링 도로명 주소 형식으로 처리하도록 개선
- locationCorrections 맵으로 지역 변환
- 기존에 지역 필터링으로 장소 조회했던 Service 수정
지역명이 도로명 주소와 일치할 경우 -> 변환 없음
도로명 주소와 다를경우 -> 도로명 주소 형식으로 변환 후 상위지역, 하위지역 필터링

[fix] 지역 필터링 개선

---

src/main/java/umc/catchy/global/config/security/SecurityConfig.java
src/main/java/umc/catchy/infra/aws/health/HealthCheckController.java

- close #154 
- 로드밸런서 healthCheck를 위한 /health API 구현
- feat : healthCheck API

[chore] healthCheck API

---

src/main/java/umc/catchy/domain/category/dao/CategoryRepository.java
src/main/java/umc/catchy/domain/place/service/PlaceService.java

- close #148 
- 장소 카테고리 설정 로직 수정
- DB에 카테고리를 가져와서 설정하도록 변경

[fix] 장소 카테고리 설정 로직 수정

---

src/main/java/umc/catchy/domain/mapping/memberCategoryVote/dao/MemberCategoryVoteRepository.java
src/main/java/umc/catchy/domain/vote/api/VoteController.java
src/main/java/umc/catchy/domain/vote/service/VoteService.java
src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java

- close #164 
- 카테고리 다시 투표하기
- 투표 상태가 `IN_PORGRESS` 일 때 카테고리 재투표 구현
- 투표 상태 완료일 때 예외처리

[feature] 카테고리 다시 투표하기

---

src/main/java/umc/catchy/domain/mapping/placeCourse/api/PlaceCourseController.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dao/PlaceCourseRepositoryImpl.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoDetail.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoPreview.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoPreviewSliceResponse.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoResponse.java
src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
src/main/java/umc/catchy/domain/mapping/placeLike/converter/PlaceLikeConverter.java
src/main/java/umc/catchy/domain/mapping/placeLike/dao/PlaceLikeRepository.java
src/main/java/umc/catchy/domain/mapping/placeLike/domain/PlaceLike.java
src/main/java/umc/catchy/domain/mapping/placeLike/dto/response/PlaceLikedResponse.java
src/main/java/umc/catchy/domain/mapping/placeLike/service/PlaceLikeService.java
src/main/java/umc/catchy/domain/mapping/placeVisit/converter/PlaceVisitConverter.java
src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
src/main/java/umc/catchy/domain/mapping/placeVisit/service/PlaceVisitService.java
src/main/java/umc/catchy/domain/place/api/PlaceController.java
src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
src/main/java/umc/catchy/domain/place/dao/PlaceCustomRepository.java
src/main/java/umc/catchy/domain/place/dao/PlaceRepositoryImpl.java
src/main/java/umc/catchy/domain/place/domain/Place.java
src/main/java/umc/catchy/domain/place/service/PlaceService.java

- close #160 
- 사용자가 방문한 장소의 카테고리와 카테고리 별 평균 시간대를 반영하여 추천하는 방식임
- 방문 카테고리 빈도 순, 사용자와 장소 거리가 가까운 순으로 정렬(기존 방문 장소 제외)
- Place 테이블에 LocalTime 타입의 startTime, endTime 컬럼 추가(기존의 activeTime String 값을 파싱해서 얻어옴)
- PlaceLike 객체 추가, queryDsl에 반영
- Place 관련 Response 수정

[feature] 사용자 장소 추천 기능 구현

---

src/main/java/umc/catchy/domain/course/converter/CourseConverter.java
src/main/java/umc/catchy/domain/course/dto/response/CourseInfoResponse.java
src/main/java/umc/catchy/domain/course/service/CourseService.java

- close #173 
- 코스 상세 정보 조회 API response 변경
- memberCourse로부터 북마크 여부를 가져와 조회 할 수 있도록 함.

[fix] 코스 상세 정보 response에 북마크 여부 추가

---

.github/workflows/github-actions.yml

- close #184 
- main 브랜치에 PR 또는 push 할 경우 workflow를 수행하도록 github-actions.yml 수정
- github-actions.yml 수정

[chore] github-actions.yml 수정

---

README.md

- close #180 
- 리드미 초안 작성
- 프로젝트 소개
- 시스템 아키텍처
- ERD
- 기술스택
- 컨벤션

[docs] 리드미 작성

---

src/main/java/umc/catchy/domain/courseReview/domain/CourseReview.java
src/main/java/umc/catchy/domain/placeReview/domain/PlaceReview.java
src/main/java/umc/catchy/domain/reviewReport/service/ReviewReportService.java

- close #172 
- 리뷰 신고 시 해당 리뷰의 isReported를 true로 변경
- 서비스 로직 수정

[fix] 리뷰 신고 시 리뷰의 상태 변경

---

src/main/java/umc/catchy/domain/group/api/GroupController.java
src/main/java/umc/catchy/domain/group/service/GroupService.java
src/main/java/umc/catchy/domain/mapping/memberGroup/dao/MemberGroupRepository.java

- close #182
- 캘린더 그룹 조회 수정
- 그룹 조회 년,월로 필터링 처리

[fix] 캘린더 그룹 조회 수정

---

src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoDetail.java
src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java

- close #193 
- 장소 상세 화면 response 변경
- 북마크 여부(liked) 추가

[fix] 장소 상세 화면 response 변경

---

src/main/java/umc/catchy/domain/course/service/CourseSchedulerService.java
src/main/java/umc/catchy/domain/course/service/CourseService.java

- close #195 
- CourseSchedulerService 위치 service 패키지 안으로 수정
- 주석 정리
- CourseSchedulerService 위치 service 패키지 안으로 수정

[refactor] 패키지 위치 변경

---

src/main/java/umc/catchy/domain/courseReview/dao/CourseReviewRepositoryImpl.java
src/main/java/umc/catchy/domain/reviewReport/dto/response/MyPageReviewsResponse.java

- close #205 
- 마이페이지/ 코스 리뷰 조회 API의 response에 categories 추가
- dto 및 로직 수정

[fix] 마이페이지/코스 리뷰 조회 response 수정

---

.github/workflows/github-actions.yml

- close #207 
- 기존의 docker-compose의 모든 컨테이너를 down & up 했던 코드를 서버 app만 재시작하도록 코드 수정
- github-actions.yml 수정

[fix] github-actions.yml 수정

---

src/main/java/umc/catchy/domain/courseReview/dao/CourseReviewRepositoryImpl.java
src/main/java/umc/catchy/domain/reviewReport/dto/response/MyPageReviewsResponse.java

- close #210 
- 카테고리가 중복되어 보내지는 문제 해결
- 쿼리 수정

[fix] 마이페이지/코스 리뷰 조회 : 카테고리 중복 수정

---

src/main/java/umc/catchy/domain/course/api/CourseController.java
src/main/java/umc/catchy/domain/course/domain/Course.java
src/main/java/umc/catchy/domain/course/service/CourseService.java
src/main/java/umc/catchy/domain/mapping/memberCourse/domain/MemberCourse.java
src/main/java/umc/catchy/domain/mapping/placeVisit/converter/PlaceVisitConverter.java
src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
src/main/java/umc/catchy/domain/mapping/placeVisit/domain/PlaceVisit.java
src/main/java/umc/catchy/domain/mapping/placeVisit/service/PlaceVisitService.java
src/main/java/umc/catchy/domain/place/api/PlaceController.java

- close #209 
- 방문 체크 로직 변경
- 코스 평점 계산 로직 변경
- 방문 체크
- 코스 독립적으로 방문체크를 할 수 있도록 변경
- 그에 따라 방문체크 날짜 조회 로직도 변경 
- 장소 방문 체크 과반수 시에 코스 방문하도록 수정
- 코스 방문 시 해당 코스에 참여자 수를 증가
- 코스(DIY) 평점 로직
- 리뷰가 없는 장소에 대해 평점을 평균에 반영하지 않는다

[fix] 방문 체크 로직 / 코스(DIY) 평점 계산 로직 수정

---

src/main/java/umc/catchy/domain/courseReview/converter/CourseReviewConverter.java
src/main/java/umc/catchy/domain/courseReview/domain/CourseReview.java
src/main/java/umc/catchy/domain/placeReview/converter/PlaceReviewConverter.java
src/main/java/umc/catchy/domain/placeReview/domain/PlaceReview.java

- close #214 
- isReported가 null이 되는 문제 해결
- 로직 수정

[fix] 리뷰 생성 시 isReported가 false가 되도록 수정
