Catch-y/Spring_BE

build.gradle
src/main/java/umc/catchy/global/config/querydsl/QueryDslConfig.java

- close #7 
- QueryDsl 을 사용하기 위한 의존성 추가
- gradle에 querydsl 의존성추가(Q타입을 버전관리(GIT)에 포함하지않기 위해 gradle build 폴더아래 생성하도록 설정)
- global/config/querydsl 패키지에 QueryDslConfig 설정
- 
- 
- https://docs.google.com/document/d/1j0jcJ9EoXMGzwAA2H0b9TOvRtpwlxI5Dtn3sRtuXQas/edit?tab=t.0#heading=h.vfy9wirpglmx

feat: Querydsl 환경구성 추가

---

.github/workflows/github-actions.yml
Dockerfile
build.gradle
src/main/resources/application-local.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml

- close #9 
- Docker & Github Actions & AWS EC2를 이용한 CI/CD 파이프라인 구축
- Dockerfile 작성
- github-actions.yml 작성
- application-prod.yml 작성
- AWS에서 EC2 및 rds 구축
앞으로 해당 링크에서 스웨거 확인할 수 있습니다. 
(http://ec2-3-34-59-249.ap-northeast-2.compute.amazonaws.com:8081/swagger-ui/index.html)
로컬환경에서는 h2, 배포환경에서는 mysql 사용으로 인해 배포 환경에서 DB 드라이버 사이의 충돌 발생, 설정 별 프로필 분리를 통해 해당 문제 해결함.
[CI/CD 파이프라인 구축 with Docker]
https://velog.io/@leeeeeyeon/Github-Actions%EA%B3%BC-Docker%EC%9D%84-%ED%99%9C%EC%9A%A9%ED%95%9C-CICD-%EA%B5%AC%EC%B6%95
[설정 별 프로필 분리]
https://developerbee.tistory.com/272

[feature] CI/CD 파이프라인 구축

---

src/main/java/umc/catchy/domain/course/api/CourseController.java
src/main/java/umc/catchy/domain/course/service/CourseService.java
src/main/java/umc/catchy/domain/mapping/memberCourse/converter/MemberCourseConverter.java
src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepository.java
src/main/java/umc/catchy/domain/mapping/memberCourse/dto/response/MemberCourseResponse.java
src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java

- close #51 
- 현 로그인 상태인 사용자의 코스 조회
- AI/DIY 별로 조회
- 지역 별로 조회
- 검색한 지역이 코스의 장소들에 있는 지역일 때  
- 대카테고리 조회
-  검색한 코스들에 포함된 지역들의 대카테고리를 함께 출력
검색 예시
- AI, 시(전체), 구(전체)
- DIY, 시(전체), 구(전체)
- DIY, 서울시, 노원구
- AI, 경기도, 구리시

[feature] 사용자의 코스 조회

---

src/main/java/umc/catchy/domain/mapping/placeCourse/dao/PlaceCourseRepository.java
src/main/java/umc/catchy/domain/placeReview/service/PlaceReviewService.java

- close #57 
- 코스 평점(해당 코스에 포함되는 모든 장소 평점의 평균) 
=> 장소 평점/리뷰 생성 시점에 코스 평점을 갱신하도록 로직 구현
- 평점 계산 성능을 고려하여 JPQL을 이용해 데이터베이스 상에서 계산하도록 함.
- 코스 평점 계산 및 갱신 로직 추가
- 코스 평점 갱신에 대하여 책임 분리 원칙에 따라 CourseService에 구현할지, 기능이 실제로 실행되는 PlaceReviewService에 구현할지 고민되었음. 
=> 서비스에서 코스 평점은 장소 평점/리뷰의 생성&신고&삭제 순간에만 갱신 된다고 판단.
해당 로직을 PlaceReviewService에 구현함.
1. 갱신 로직이 PlaceReviewService에서만 필요하다면?
평점 갱신 작업이 단순하고 PlaceReviewService 외 다른 서비스에서 절대 사용되지 않는다면, PlaceReviewService가 CourseRepository를 직접 사용하는 것이 더 간단하고 적절합니다.
2. 갱신 로직이 재사용될 가능성이 있다면?
현재는 PlaceReviewService에서만 필요하더라도, 평점 갱신 로직이 다른 서비스나 유스케이스에서도 필요해질 가능성이 있다면, CourseService를 통해 구현하는 것이 좋습니다.

[fix] 코스 평점 계산 로직 추가

---

src/main/java/umc/catchy/domain/mapping/placeCourse/api/PlaceCourseController.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfo.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoDetail.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoResponse.java
src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
src/main/java/umc/catchy/domain/member/dto/response/SignUpResponse.java
src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
src/main/java/umc/catchy/domain/place/dao/PlaceRepository.java
src/main/java/umc/catchy/domain/place/domain/Place.java
src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
src/main/resources/application-prod.yml

- close #76 
- 사용자 위치 기반 장소 검색
- 사용자 위치 기반 장소 검색
- 사용자의 위도, 경도, 검색 키워드를 통해 장소 정보를 받아온다 
- 예를 들어, 스타벅스를 검색하면 내 위치 반경 5km 이내의 스타벅스를 거리순으로 정렬
- 지역 기반 장소 검색
-  사용자의 검색 키워드를 통해 장소 정보를 받아온다
- 예를 들어, 서울시 동작구 스타벅스를 검색하면 관련도 높은 순으로 정렬
- 장소 이미지 저장 로직
- TMAP에서 받아온 장소의 주소와 가게 이름 정보를 통해 구글 맵 API로 GET 요청을 하여 가게를 찾음
- 해당 response에서 받아온 photo_reference 값을 구글 맵 API에 GET 요청을 하여 이미지를 받아옴
- url에는 API KEY 값이 포함되어 GOOGLE_API_KEY로 치환하여 저장하였음
- 프론트에서는 GOOGLE_API_KEY를 실제 앱 키로 바꾸어 이미지를 가져올 것임
- 장소 저장 로직 설명
1. 사용자가 장소를 검색 
2. TMAP에서 관련 장소를 모두 불러옴
3. 그 장소 리스트를 스트림으로 검사해서 PlaceRepository에 있는지 검사(findByPoiId)
4. 있으면 그 장소 데이터를 가져오고
5. 없으면 TMAP에서 제공해준 Place 정보와 구글에서 해당 장소의 이미지를 가져와 Place를 저장.
- 지역명 기반 검색 결과: 서울시 동작구 스타벅스
- 내 위치 기반 검색 결과: 서울시 강남구 위치에서 '고기' 검색
- placeId로 placeDetail 불러오기
- TMAP api에서 페이지 별로 장소를 받을 수 있어서 …

[feature] 장소 검색 및 상세 정보 보기

---

src/main/java/umc/catchy/domain/mapping/memberCourse/api/MemberCourseController.java
src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepository.java
src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepositoryCustom.java
src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepositoryImpl.java
src/main/java/umc/catchy/domain/mapping/memberCourse/dto/response/MemberCourseResponse.java
src/main/java/umc/catchy/domain/mapping/memberCourse/service/MemberCourseService.java

- close #70  
- 찜한 코스 조회 (무한 스크롤 구현)
- querydsl을 적용해 북마크된 코스 무한 스크롤로 구현.
- 성공 시 다음과 같이 나옴 (querystring 으로 pageSize를 넘겨주고, 마지막 페이지가 아닌 경우 마지막 코스id를 넘겨주면 그 이후 데이터로 보여준다. )
- 현재 custumrepo에서 데이터를 가져올때 N+1 문제가 발생할 수 있어 성능상 문제가 있다. 이 부분에 대해 수정해야 될 필요가 있을 것 같다.
- 또한 마이페이지에 대한 API를 어디에 배치할지 몰라 매핑테이블 도메인에 설정했는데 나중에 이 부분에 대해 논의 할 필요가 있을 것 같다.
-

[feature] 찜한 코스 조회

---

src/main/java/umc/catchy/domain/mapping/placeCourse/api/PlaceCourseController.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dao/PlaceCourseRepository.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dao/PlaceCourseRepositoryCustom.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dao/PlaceCourseRepositoryImpl.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoResponse.java
src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java

- close #71 
- 좋아요한 장소 조회 무한 스크롤 
- querydsl을 적용해 좋아요한 장소들을 무한 스크롤 형태로 구현했다.
- 성공 시 다음과 같이 나옴
- fetch join을 통해 n+1문제를 해결하려고 했으나 에러가 발생해 groupby를 통해 리뷰의 평점 평균, 리뷰 개수를 구했다. 
- 여러개의 엔티티간 조인이 있어서 어려움이 있었다.
- https://breakcoding.tistory.com/407

[feature] 좋아요한 장소 조회

---

src/main/java/umc/catchy/domain/mapping/memberCourse/api/MemberCourseController.java
src/main/java/umc/catchy/domain/mapping/memberCourse/dto/response/MemberCourseSliceResponse.java
src/main/java/umc/catchy/domain/mapping/memberCourse/service/MemberCourseService.java
src/main/java/umc/catchy/domain/mapping/placeCourse/api/PlaceCourseController.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoSliceResponse.java
src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java

- close #95 
- 무한 스크롤 응답 구조 수정
- 무한 스크롤 응답 구조 수정
- record 클래스로 SliceDTO 구조를 만듬 (Slice와 last를 받아서 새로 반환)
- 성공
- 
-

[fix] 스크롤 응답 구조 통일

---

src/main/java/umc/catchy/domain/course/dto/response/GptCourseInfoResponse.java
src/main/java/umc/catchy/domain/course/service/CourseService.java

- close #110 
- 코스 생성 시 코스 평점 반영
- 장소 평점 합 / 장소 개수로 코스 평점 계산
- 소수점 둘째 자리에서 반올림하여 코스 평점 저장
- 장소 평점이 0 또는 null인 경우 리뷰가 없다고 간주하고 평점 계산에서 제외
- `participantsNumber` 기본값을 0으로 설정

[fix] 코스 평점

---

src/main/java/umc/catchy/domain/courseReview/converter/CourseReviewConverter.java
src/main/java/umc/catchy/domain/courseReview/dto/response/PostCourseReviewResponse.java
src/main/java/umc/catchy/domain/courseReview/service/CourseReviewService.java
src/main/java/umc/catchy/domain/placeReview/converter/PlaceReviewConverter.java
src/main/java/umc/catchy/domain/placeReview/domain/PlaceReview.java
src/main/java/umc/catchy/domain/placeReview/dto/request/PostPlaceReviewRequest.java
src/main/java/umc/catchy/domain/placeReview/dto/response/PostPlaceReviewResponse.java
src/main/java/umc/catchy/domain/placeReview/service/PlaceReviewService.java

- close #135 
- 리뷰 작성 시, 방문 날짜를 가져오는 방식 수정
- 코스 리뷰 : visitedDate 관련 로직 delete
- 장소 리뷰 : request로 visitedDate를 받고 이를 PlaceReview에 저장
1. 코스 리뷰
2. 장소 리뷰
- 인기 코스 조회 시 넣어놨던 데이터 중 memberCourse에 member와 course가 중복되는 데이터가 있어서 Query did not return a unique result: 2 results were returned 에러가 발생 => 데이터를 지워서 해결함.

[fix] 리뷰 작성 : 방문 날짜 로직 수정

---

src/main/java/umc/catchy/domain/courseReviewImage/dao/CourseReviewImageRepository.java
src/main/java/umc/catchy/domain/placeReviewImage/dao/PlaceReviewImageRepository.java
src/main/java/umc/catchy/domain/reviewReport/api/ReviewReportController.java
src/main/java/umc/catchy/domain/reviewReport/converter/ReviewReportConverter.java
src/main/java/umc/catchy/domain/reviewReport/dao/ReviewReportRepository.java
src/main/java/umc/catchy/domain/reviewReport/domain/ReviewReport.java
src/main/java/umc/catchy/domain/reviewReport/domain/ReviewType.java
src/main/java/umc/catchy/domain/reviewReport/dto/request/PostReviewReportRequest.java
src/main/java/umc/catchy/domain/reviewReport/dto/response/DeleteReviewResponse.java
src/main/java/umc/catchy/domain/reviewReport/dto/response/PostReviewReportResponse.java
src/main/java/umc/catchy/domain/reviewReport/service/ReviewReportService.java
src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java

- close #139 
- 리뷰 신고 및 삭제 기능 구현
- ReviewReport 엔티티 생성
- 리뷰 신고 기능 구현
- 리뷰 삭제 기능 구현 : 삭제 이전에 이미지와 reviewReport 정보도 함께 삭제
- 리뷰 타입에 따라 다른 로직을 수행하는데, 비슷한 코드가 많아서 Review라는 상위 엔티티를 만들고 courseReview와 placeReview에 대한 로직을 제네릭하게 만들면 코드를 더 깔끔하게 만들 수 있을 것 같음.
- 신고된 리뷰에 대해 상태가 변경되고 조회가 불가능하게 조회 코드 및 엔티티를 수정할 필요가 있음.
- 리뷰 신고 중복 검사 로직 추가 필요

[feat] 리뷰 신고/삭제 API

---

src/main/java/umc/catchy/domain/course/service/CourseService.java
src/main/java/umc/catchy/domain/mapping/memberCourse/domain/MemberCourse.java

- close #153 
- AI 추천 코스 생성 시 member_course 테이블에 저장
- 영속성 문제때문에 MemberCourse 테이블에 CascadeType.ALL 제거했습니다.
- AI 추천코스 생성되면 member_course 테이블에 저장되게 했습니다.

[fix] AI 추천 코스 생성 시 member_course 테이블에 저장

---

src/main/java/umc/catchy/domain/mapping/memberActivetime/dao/MemberActiveTimeRepository.java
src/main/java/umc/catchy/domain/mapping/memberCategory/dao/MemberCategoryRepository.java
src/main/java/umc/catchy/domain/mapping/memberCategoryVote/dao/MemberCategoryVoteRepository.java
src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepository.java
src/main/java/umc/catchy/domain/mapping/memberGroup/dao/MemberGroupRepository.java
src/main/java/umc/catchy/domain/mapping/memberLocation/dao/MemberLocationRepository.java
src/main/java/umc/catchy/domain/mapping/memberPlaceVote/dao/MemberPlaceVoteRepository.java
src/main/java/umc/catchy/domain/mapping/memberStyle/dao/MemberStyleRepository.java
src/main/java/umc/catchy/domain/member/api/MemberController.java
src/main/java/umc/catchy/domain/member/service/MemberService.java

- close #152 
- 회원 탈퇴 로직 수정
- 회원 탈퇴 시 관련 연관 테이블 삭제
- 애플 탈퇴 시 인가 코드를 받아서 탈퇴 (인가코드에 유효기간이 있음)
- 애플 로그인 -> 인가 코드 서버로 전달 -> 회원 탈퇴

[fix] 회원 탈퇴 로직 수정

---

src/main/java/umc/catchy/domain/course/api/CourseController.java
src/main/java/umc/catchy/domain/course/service/CourseService.java
src/main/java/umc/catchy/domain/course/service/GPTCourseService.java
src/main/java/umc/catchy/domain/member/domain/Member.java

- close #166 
- 홈 화면에서 AI가 생성한 코스가 "내 코스 조회"에서 제외되도록 수정  
- AI 추천 코스 요청 시 `gpt_count` 증가 로직 추가  
- 이미지 생성 프롬프트 개선 (코스 설명에 맞게 최적화)  
- 홈 화면에서 제공하는 AI 추천 코스를 `MemberCourse` 테이블에 저장하지 않도록 변경
- "내 코스 조회" API에서 홈 화면의 AI 생성 코스가 조회되지 않도록 함
- AI 추천 코스를 요청할 때 `gpt_count`가 증가하도록 수정 
- 이미지 생성 프롬프트 최적화
- 이미지 생성이 더 디테일해지면서 소요 시간이 다소 증가

[fix] 홈 화면의 AI 코스 - "내 코스 조회"에서 제외

---

src/main/java/umc/catchy/CatchyApplication.java
src/main/java/umc/catchy/domain/course/dto/response/GptCourseInfoResponse.java
src/main/java/umc/catchy/domain/course/service/CourseService.java
src/main/java/umc/catchy/domain/place/dao/PlaceCustomRepository.java
src/main/java/umc/catchy/domain/place/dao/PlaceRepositoryImpl.java

- close #176 
- AI 추천 코스 생성 응답 dto 수정
- QueryDSL을 활용해 장소, 카테고리, 리뷰 개수를 한 번에 조회하는 메서드 사
- 응답(GptCourseInfoResponse)에 포함되는 장소 정보에 카테고리, 이미지, 평점, 리뷰 개수를 포함하도록 수정
- ![image](https://github.com/user-attachments/assets/cc7e0a0b-2e57-4394-80e0-b767eb89fb8a)
- 
-

[fix] AI 추천 코스 응답 수정

---

src/main/java/umc/catchy/domain/place/dao/PlaceCustomRepository.java
src/main/java/umc/catchy/domain/place/dao/PlaceRepositoryImpl.java
src/main/java/umc/catchy/domain/vote/api/VoteController.java
src/main/java/umc/catchy/domain/vote/dto/response/GroupPlaceResponse.java
src/main/java/umc/catchy/domain/vote/service/VoteService.java

- close #179 
- 카테고리 별 장소 확인 무한스크롤 구현
- 카테고리 별 장소 확인 무한스크롤 구현으로 수정했습니다.
- QueryDSL을 활용해 카테고리 필터링 + 투표 수 정렬 리팩토링 했습니다.
- 마지막 페이지일 때 ![](https://github.com/user-attachments/assets/a0e98e2e-2423-4783-9f64-5c0948b2c377)
- 작업하며 발생한 에러 혹은 궁금한 사항이 있다면 적어주세요.
- 기능 구현 or 수정하며 참고한 사항이 있다면 적어주세요.

[fix] 카테고리 별 장소 확인 무한스크롤

---

src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepositoryCustom.java
src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepositoryImpl.java
src/main/java/umc/catchy/domain/reviewReport/api/ReviewReportController.java
src/main/java/umc/catchy/domain/reviewReport/dto/response/MyPageReviewsResponse.java
src/main/java/umc/catchy/domain/reviewReport/service/ReviewReportService.java

- close #186 
- 장소리뷰 조회, 카테고리를 response에 추가
- 장소리뷰 조회/코스리뷰 조회 API 분리 - 마이페이지
- response 수정
- API 분리 및 장소 리뷰 정렬 방식 수정
- 코스 리뷰
- 장소 리뷰

[fix] 마이페이지/리뷰 조회 API -  코스리뷰/장소리뷰 분리

---

src/main/java/umc/catchy/CatchyApplication.java
src/main/java/umc/catchy/domain/course/api/CourseController.java
src/main/java/umc/catchy/domain/course/api/CourseSchedulerService.java
src/main/java/umc/catchy/domain/course/dao/CourseRepository.java
src/main/java/umc/catchy/domain/course/service/CourseService.java
src/main/java/umc/catchy/domain/course/service/GPTCourseService.java
src/main/java/umc/catchy/infra/aws/s3/AmazonS3Manager.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml

- close #189 
- 홈 화면 추천 코스 스케줄러 구현
- generateCourseAutomatically 메서드를 오버로딩하여 API 호출과 스케줄러 실행 시 각각 다른 방식으로 사용자 ID를 처리하도록 했습니다. 
- 스케줄러 실행 시에는 직접 memberId를 받아 사용하여 비인증 환경에서 정상적으로 동작하기 위함
- 비동기 요청 타임아웃 60초로 늘렸습니다.
- Dall-E `429 Too Many Requests` 에러 발생 시 재시도 로직 추가했습니다.
- 스케줄러 수요일 00시 30분 00초로 설정했을 때 테스트

[feature] 스케줄러 구현

---

src/main/java/umc/catchy/domain/jwt/service/BlackTokenRedisService.java
src/main/java/umc/catchy/domain/jwt/service/RedisTokenService.java
src/main/java/umc/catchy/domain/mapping/placeLike/dao/PlaceLikeRepository.java
src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
src/main/java/umc/catchy/domain/member/dao/MemberRepository.java
src/main/java/umc/catchy/domain/member/domain/Member.java
src/main/java/umc/catchy/domain/member/dto/response/SignUpResponse.java
src/main/java/umc/catchy/domain/member/service/MemberService.java
src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
src/main/java/umc/catchy/global/util/JwtUtil.java
src/main/java/umc/catchy/infra/config/security/JwtAuthenticationFilter.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml

- close #177 
- 효율적으로 DB를 활용하기 위해 redis를 사용했습니다.
- 액세스 토큰은 db에서, 리프레시 토큰은 redis에서 관리
- 회원가입: 리프레시 토큰 redis 저장
- 로그인: 기존 리프레시 토큰 redis 삭제, 새 액세스 토큰 db저장, 새 리프레시 토큰 redis 저장
- 로그아웃: 리프레시 토큰 redis 삭제, 액세스 토큰 블랙리스트(redis)
- 토큰 재발급: 기존 토큰 무효화(각각 redis 삭제, 블랙리스트 추가), 새로운 토큰 저장(각각 redis, db 저장) 
- 회원탈퇴: 기존 토큰 무효화
Key 값을 통해 redis에 잘 저장되는거 확인
https://eesko.tistory.com/353
https://onethejay.tistory.com/34

[feature] redis를 통한 refreshToken 관리

---

src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java

- close #201 
- category 존재하지 않을 시 null 반환하도록 변경
- place에서 없는 값은 null로 통일

[fix] category 존재하지 않을 시 null 반환하도록 변경

---

Dockerfile

- close #198 
- Dockerfile 수정을 통한 이미지 사이즈 최적화 수행
- 도커 빌드 이미지 베이스 변경
openjdk:17 ▶️ eclipse-temurin:17-jdk-alpine
- 멀티 스테이지 빌드 적용
eclipse-temurin:17-jdk-alpine & eclipse-temurin:17-jre-alpine
443.39MB ▶️ 291.79MB
1. 도커 빌드 이미지 베이스 변경 : 같은 빌드 파일로부터 139.49MB 만큼 사이즈를 줄임. & 기능 수행이 잘 되는 것 또한 확인.
2. 멀티 스테이지 빌드 적용 : 이미지 사이즈를 151.6MB 만큼 줄임. & 기능 수행이 잘 되는 것을 확인
빌드 후 배포 환경 테스트에서 로그인 / 인기코스 조회 / S3 업로드 및 삭제 API를 통해 기능 수행을 확인함.
만약 배포 환경에서 API 실행했을 때 서버가 터진다면 알려주세요~
- https://octoping.tistory.com/58
- GPT

[chore] 도커 이미지 사이즈 최적화

---

src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoContainRelevance.java
src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoContainRelevanceScoreSliceResponse.java
src/main/java/umc/catchy/domain/place/api/PlaceController.java
src/main/java/umc/catchy/domain/place/dao/PlaceCustomRepository.java
src/main/java/umc/catchy/domain/place/dao/PlaceRepositoryImpl.java
src/main/java/umc/catchy/domain/place/service/PlaceService.java

- close #169 
- 홈 화면 기능인 장소이름/카테고리이름으로 장소를 검색하는 기능 API 입니다.
- 검색어가 장소명이랑 아예 일치하면 관련성 100점, 장소명이 포함되면 80점, 카테고리가 일치하면 60점, 카테고리를 포함하면 40점, 아무것도 일치하지 않으면 0점으로 관련도를 파악했습니다.
- query string 으로 마지막 장소Id와 해당장소와 검색어간의 연관도를 입력받아 다음 Page를 가져올 수 있습니다.
- 정렬순은 연관도를 우선으로 정렬하였고, 연관도가 일치하는경우 PlaceId를 기준으로 내림차순으로 정렬하였습니다.
키워드가 없거나, 해당 키워드를 포함하는 장소 데이터가 없는경우 
- 현재 검색어로 장소이름을 포함하거나 일치하는 경우, 카테고리가 일치하거나 포함하는 경우는 데이터로 불러올 수 있습니다. 하지만 유사한 장소명 또는 연관 장소는 불러오지 못합니다. 이는 현재 기술적 문제로 나중에 Elastic Search를 도입해 검색 성능을 더욱 개선하도록 해야겠습니다.
-

[feature] 장소이름/카테고리 검색을 통한 장소 검색
